name: Client Deploy

on:
  push:
    paths:
      - "./client/*"
      - ".github/workflows/client_deploy.yml"

jobs:
  linter:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install
        run: yarn install --immutable --immutable-cache --check-cache
      - name: run linter
        run: yarn run lint
  
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
        working-directory: ./client
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Build
        run: yarn run build
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./client
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
        env:
          VITE_SERVER_URI: https://air-art.onrender.com
